export const actions = {
  // * FETCH_DATA
  FETCH_DATA_PROJECTS_REQUEST: "FETCH_DATA_PROJECTS_REQUEST",
  FETCH_DATA_PROJECTS_SUCCESS: "FETCH_DATA_PROJECTS_SUCCESS",
  FETCH_DATA_PROJECTS_FAILURE: "FETCH_DATA_PROJECTS_FAILURE",
};
