export const actions = {
  //CATEGORIE_CREATE
  CATEGORIE_CREATE_REQUEST: "CATEGORIE_CREATE_REQUEST",
  CATEGORIE_CREATE_SUCCESS: "CATEGORIE_CREATE_SUCCESS",
  CATEGORIE_CREATE_FAIL: "CATEGORIE_CREATE_FAIL",
  CATEGORIE_CREATE_RESET: "CATEGORIE_CREATE_RESET",
  //CATEGORIE_EDIT
  CATEGORIE_EDIT_REQUEST: "CATEGORIE_EDIT_REQUEST",
  CATEGORIE_EDIT_SUCCESS: "CATEGORIE_EDIT_SUCCESS",
  CATEGORIE_EDIT_FAIL: "CATEGORIE_EDIT_FAIL",
  CATEGORIE_EDIT_RESET: "CATEGORIE_EDIT_RESET",
  //CATEGORIE_LIST
  CATEGORIE_LIST_REQUEST: "CATEGORIE_LIST_REQUEST",
  CATEGORIE_LIST_SUCCESS: "CATEGORIE_LIST_SUCCESS",
  CATEGORIE_LIST_FAIL: "CATEGORIE_LIST_FAIL",
  CATEGORIE_LIST_RESET: "CATEGORIE_LIST_RESET",
  //CATEGORIE_DETAILS
  CATEGORIE_DETAILS_REQUEST: "CATEGORIE_DETAILS_REQUEST",
  CATEGORIE_DETAILS_SUCCESS: "CATEGORIE_DETAILS_SUCCESS",
  CATEGORIE_DETAILS_FAIL: "CATEGORIE_DETAILS_FAIL",
  CATEGORIE_DETAILS_RESET: "CATEGORIE_DETAILS_RESET",
  //CATEGORIE_DELETE
  CATEGORIE_DELETE_REQUEST: "CATEGORIE_DELETE_REQUEST",
  CATEGORIE_DELETE_SUCCESS: "CATEGORIE_DELETE_SUCCESS",
  CATEGORIE_DELETE_FAIL: "CATEGORIE_DELETE_FAIL",
  CATEGORIE_DELETE_RESET: "CATEGORIE_DELETE_RESET",
};
