export  const actions = {
    //PROYECT_CREATE
    PROYECT_CREATE_REQUEST: "PROYECT_CREATE_REQUEST",
    PROYECT_CREATE_SUCCESS: "PROYECT_CREATE_SUCCESS",
    PROYECT_CREATE_FAIL: "PROYECT_CREATE_FAIL",
    PROYECT_CREATE_RESET: "PROYECT_CREATE_RESET",
    //PROYECT_EDIT
    PROYECT_EDIT_REQUEST: "PROYECT_EDIT_REQUEST",
    PROYECT_EDIT_SUCCESS: "PROYECT_EDIT_SUCCESS",
    PROYECT_EDIT_FAIL: "PROYECT_EDIT_FAIL",
    PROYECT_EDIT_RESET: "PROYECT_EDIT_RESET",
    //PROYECT_LIST
    PROYECT_LIST_REQUEST: "PROYECT_LIST_REQUEST",
    PROYECT_LIST_SUCCESS: "PROYECT_LIST_SUCCESS",
    PROYECT_LIST_FAIL: "PROYECT_LIST_FAIL",
    PROYECT_LIST_RESET: "PROYECT_LIST_RESET",
    //PROYECT_DETAILS
    PROYECT_DETAILS_REQUEST: "PROYECT_DETAILS_REQUEST",
    PROYECT_DETAILS_SUCCESS: "PROYECT_DETAILS_SUCCESS",
    PROYECT_DETAILS_FAIL: "PROYECT_DETAILS_FAIL",
    PROYECT_DETAILS_RESET: "PROYECT_DETAILS_RESET",
    //PROYECT_DELETE
    PROYECT_DELETE_REQUEST: "PROYECT_DELETE_REQUEST",
    PROYECT_DELETE_SUCCESS: "PROYECT_DELETE_SUCCESS",
    PROYECT_DELETE_FAIL: "PROYECT_DELETE_FAIL",
    PROYECT_DELETE_RESET: "PROYECT_DELETE_RESET",
  };
  