export  const actions = {
  //USER_LOGIN
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGIN_RESET: "USER_LOGIN_RESET",
  USER_LOGOUT: "USER_LOGOUT",
};
